insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'11:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'11:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'12:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'12:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'13:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'13:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'14:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'14:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'15:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'15:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'16:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'16:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'17:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'17:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'18:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'18:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'19:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'19:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'20:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'20:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'21:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'21:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'22:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'22:30','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'23:00','Roller Coaster',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (101,'23:30','Roller Coaster',10);

insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'11:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'11:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'12:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'12:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'13:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'13:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'14:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'14:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'15:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'15:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'16:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'16:30','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'17:00','Transformers',10);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (102,'17:30','Transformers',10);

insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'11:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'11:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'12:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'12:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'13:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'13:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'14:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'14:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'15:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'15:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'16:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'16:30','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'17:00','Bumper Cars',15);
insert into rides(RIDE_ID,START_TIME,RIDE_NAME,RIDE_CAPACITY) values (103,'17:30','Bumper Cars',15);

insert into user(USER_NAME) values ('Mark');
insert into user(USER_NAME) values ('Tony');
insert into user(USER_NAME) values ('Jhon');
insert into user(USER_NAME) values ('Sam');
insert into user(USER_NAME) values ('Nor');
insert into user(USER_NAME) values ('Rawn');
insert into user(USER_NAME) values ('Harry');
insert into user(USER_NAME) values ('Shawn');
insert into user(USER_NAME) values ('Rock');
insert into user(USER_NAME) values ('Mickey');
insert into user(USER_NAME) values ('Henry');
